services:
  - type: web
    name: pontia-mlops-marvinbernal
    runtime: python
    plan: free
    region: frankfurt
    rootDirectory: deployment
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8080
    envVars:
      - key: GITHUB_REPO
        value: Marliakanemon/pontia-mlops-marvinbernal
