name: Deploy Model

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Model"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Solo despliega si el Build anterior fue un éxito
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        # Inyección del secreto
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Disparando despliegue en Render..."
          # Usamos la variable inyectada
          curl -X POST $RENDER_DEPLOY_HOOK
